world=/var/lib/terraria/worlds/world.wld
autocreate=3
seed=
worldname=world
difficulty=2
maxplayers=16
port=7777
password=
motd=
worldpath=/var/lib/terraria/worlds
banlist=
secure=1
language=en-US
upnp=0
npcstream=60
priority=3
